### ISSUE TITLE
assertion failed train_data_weights train_data_list

### ISSUE THREAD

**Issue by theashworld** [facebookresearch/anli#11]
Setup exactly as described and followed all steps. Then ... 

```
$ python src/nli/training.py  --model_class_name "roberta-large" -n 1 -g 1 -nr 0 --max_length 256 --gradient_accumulation_steps 2 --per_gpu_train_batch_size 16 --per_gpu_eval_batch_size 16   --save_prediction --train_data snli_train:none,mnli_train:none    --train_weights 1  --eval_data snli_dev:none   --eval_frequency 2000    --experiment_name "roberta-large|snli|nli"
Downloading: 100%|██████████████████████████████████████████████████████████████████████| 899k/899k [00:00<00:00, 4.99MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 3.96MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████| 482/482 [00:00<00:00, 289kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████| 1.43G/1.43G [04:09<00:00, 5.71MB/s]
Some weights of the model checkpoint at roberta-large were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-large and are newly initialized: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Load Jsonl: /home/qblocks/shan/anli/data/build/snli/train.jsonl
549367it [00:02, 191192.35it/s]
Load Jsonl: /home/qblocks/shan/anli/data/build/mnli/train.jsonl
392702it [00:02, 179624.89it/s]
Load Jsonl: /home/qblocks/shan/anli/data/build/snli/dev.jsonl
9842it [00:00, 186058.95it/s]
Traceback (most recent call last):
  File "src/nli/training.py", line 852, in <module>
    main()
  File "src/nli/training.py", line 375, in main
    mp.spawn(train, nprocs=args.gpus_per_node, args=(args,))  # spawn how many process in this node
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/qblocks/shan/anli/src/nli/training.py", line 478, in train
    assert len(train_data_weights) == len(train_data_list)
AssertionError
```

**Comment by theashworld** [comment]
ok looks like `--train_weights 1` is the culprit, removing that arg solves the issue. Still an issue, but at least there's a workaround, so low priority, I guess

**Comment by easonnie** [comment]
@theashworld Thanks for pointing it out. The instructions have been updated. The number of values for `--train_weights` needs to match the number of items in `--train_data`.
