### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by theashworld** [facebookresearch/anli#12]
With the command
```
$ python src/nli/training.py  --model_class_name "roberta-large" -n 1 -g 1 -nr 0 --max_length 256 --gradient_accumulation_steps 2 --per_gpu_train_batch_size 16 --per_gpu_eval_batch_size 16   --save_prediction --train_data snli_train:none,mnli_train:none     --eval_data snli_dev:none   --eval_frequency 2000    --experiment_name "roberta-large|snli|nli"
```

I get the error
```
                                                                                                                           Pro:global_rank:0|local_rank:0|node_rank:0||Print: anli_r1_dev Acc: 488 1000 0.488   | 23999/40717 [17:36<11:31, 24.17it/s]
Pro:global_rank:0|local_rank:0|node_rank:0||Print: anli_r2_dev Acc: 395 1000 0.395
Pro:global_rank:0|local_rank:0|node_rank:0||Print: anli_r3_dev Acc: 504 1200 0.42
Save to Jsonl: /home/qblocks/shan/anli/saved_models/10-07-07:30:24_roberta-base|snli+mnli+fnli+r1*10+r2*20+r3*10|nli/predictions/e(0)|i(6000)|anli_r1_dev#(0.488)|anli_r2_dev#(0.395)|anli_r3_dev#(0.42)/anli_r1_dev.jsonl
Save to Jsonl: /home/qblocks/shan/anli/saved_models/10-07-07:30:24_roberta-base|snli+mnli+fnli+r1*10+r2*20+r3*10|nli/predictions/e(0)|i(6000)|anli_r1_dev#(0.488)|anli_r2_dev#(0.395)|anli_r3_dev#(0.42)/anli_r2_dev.jsonl
Save to Jsonl: /home/qblocks/shan/anli/saved_models/10-07-07:30:24_roberta-base|snli+mnli+fnli+r1*10+r2*20+r3*10|nli/predictions/e(0)|i(6000)|anli_r1_dev#(0.488)|anli_r2_dev#(0.395)|anli_r3_dev#(0.42)/anli_r3_dev.jsonl
Iteration:  72%|█████████████████████████████████████████████████▊                   | 29374/40717 [21:40<08:22, 22.58it/s]
Epoch:   0%|                                                                                         | 0/2 [21:40<?, ?it/s]
Traceback (most recent call last):
  File "src/nli/training.py", line 852, in <module>
    main()
  File "src/nli/training.py", line 368, in main
    train(0, args)
  File "src/nli/training.py", line 630, in train
    labels=batch['y'])
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qblocks/.local/lib/python3.6/site-packages/transformers/modeling_roberta.py", line 344, in forward
    output_hidden_states=output_hidden_states,
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qblocks/.local/lib/python3.6/site-packages/transformers/modeling_bert.py", line 762, in forward
    output_hidden_states=output_hidden_states,
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qblocks/.local/lib/python3.6/site-packages/transformers/modeling_bert.py", line 439, in forward
    output_attentions,
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qblocks/.local/lib/python3.6/site-packages/transformers/modeling_bert.py", line 389, in forward
    layer_output = self.output(intermediate_output, attention_output)
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qblocks/.local/lib/python3.6/site-packages/transformers/modeling_bert.py", line 345, in forward
    hidden_states = self.dense(hidden_states)
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/qblocks/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1612, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

**Comment by easonnie** [comment]
@theashworld Thanks for pointing it out. This error might be caused by fact that your GPU is out of memory. Did you try `roberta-base` for the `--model_class_name` argument.

**Comment by theashworld** [comment]
yes this is not occurring anymore on a machine with no other GPU process running. Thanks!
